### ISSUE TITLE
Add NETN FOM Module to extend RPR SE

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#15]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date | Resolution | Last Update
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
COM_008 | NETN FOM Module for Synthetic   Environment |   | The Synthetic Environment needs   to be extended in NETN. Following object class that inherits from RPR object   classes is suggested: CheckPoint (inherits from RPR-SE_v2   EnvironmentObject.PointObject.OtherPointObject) | TC | Add CheckPoint (inherits from   RPR-SE_v2 EnvironmentObject.PointObject.OtherPointObject) | Tested in Viking 18. Proposal   exist. | Lennart Olsson, lennart@pitch.se | 2017-07-06 |   |

**Comment by lofstrandbjorn** [comment]
Added representation of CheckPoint to NETN-Physical FOM Module. No NETN-SE Module added.
