### ISSUE TITLE
Add support for Crisis Management and Disasters

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#19]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date | Resolution | Last Update
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
COM_012 | CMDR Modules |   | MSG-147 have identified need to   extend NETN FAFD with additional chapters and new and/or updated FOM Modules   to support simulation of aspects related to Crisis Management and Disaster   Response. These may include the following areas of interest: Geophhysical:   Earthquake, Mass Movement, Vocanic activity; Hydrological: Flood, Landslide,   Wave Action; Meterological: Storm, Extreme temperature, Fog; Climatological:   Drought, Glacial lake outburst, Wildfire; Biological: Animal Accident,   Epidemic, Insect infestation; Extra-terrestrial: Impact, Space Weather | TC | Develop modules in collaboration   with MSG-146          Geophhysical: Earthquake, Mass Movement, Vocanic activity     Hydrological: Flood, Landslide, Wave Action     Meterological: Storm, Extreme temperature, Fog     Climatological: Drought, Glacial lake outburst, Wildfire     Biological: Animal Accident, Epidemic, Insect infestation     Extra-terrestrial: Impact, Space Weather |   | Björn Löfstrand, bjornl@pitch.se | 2017-07-06 |   |

**Comment by lofstrandbjorn** [comment]
No FOM Module input received from MSG-147 so far.

**Comment by lofstrandbjorn** [comment]
New NETN-DIM Module (NETN DIsaster Module) proposal to be coordinated with previous members of MSG-147. NETN-CBRN will depend on NETN-DIM
