### ISSUE TITLE
Add support for AIS information

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#20]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date | Resolution | Last Update
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
COM_013 | AIS FOM Module |   | Add representation of simulated   ship traffic with AIS information. FOM Module used in Viking 18 exists. | TC | Develop AIS FOM Module. | A proposed version was tested in   Viking 18 | Tom van den Berg,   tom.vandenberg@tno.nl | 2018-05-01 |   |

**Comment by lofstrandbjorn** [comment]
NETN-AIS FOM Module added.
