### ISSUE TITLE
Align NETN Modules with HLA 4

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#23]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date
-- | -- | -- | -- | -- | -- | -- | -- | --
COM_021 | Align NETN FOM with HLA 4 |   | Updates of HLA will influence   the way NETN FOM modules are designed. | TC | Adapt NETN to utilize the latest   versions of HLA with backward compatibility. |   | Björn Löfstrand, bjornl@pitch.se | 2018-06-20

**Comment by lofstrandbjorn** [comment]
Issue on-hold until release of HLA 4

**Comment by lofstrandbjorn** [comment]
The primary module targeted for this update is the NETN-Physical with extensions to the RPR-FOM Physical entity leaf classes. There are also classes in other modules that depend on RPR-FOM or other NETN modules which will be affected but I suggest splitting this issue into multiple issues for each module. I recommend starting with NETN-Physical.

**Comment by lofstrandbjorn** [comment]
Defined UniqueId in NETN-BASE on HLAobjectRoot class.

**Comment by lofstrandbjorn** [comment]
Define attributes using HLA4 FOM merging. Keep subclasses NETN_Aggregate, and all NETN extensions of Physical Platform classes for backward compatibility. Define attributes at appropriate level and in appropriate modules.
