### ISSUE TITLE
Rename NETN HCBML to NETN-CBML or NETN-C2SIM?

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#24]
PCR # | Short Description | Module/Page | Problem/Proposal | TC/EC | Action | Note | Submitted by | Submission Date
-- | -- | -- | -- | -- | -- | -- | -- | --
COM_004 | Change name of FOM module | NETN FAFD v2.0 D4 | In chapter 7.1. Use term CBML   FOM module instead of NETN-HCBML FOM Module. | EC | Change name of FOM module | Comment carried over from review   of NETN FAFD v2.0 D4 | Tom van den Berg,   tom.vandenberg@tno.nl | 2014-11-14

**Comment by lofstrandbjorn** [comment]
The NETN-HCBML is currently not in the GitHub.

**Comment by lofstrandbjorn** [comment]
DROP IT

**Comment by lofstrandbjorn** [comment]
This issues is reopened to manage the question of introducing NETN-C2SIM FOM module to initially represent reporting interactions mapped to the SISO C2SIM Military Ontology.

**Comment by lofstrandbjorn** [comment]
We are currently exploring using NETN-ETR to cover the C2SIM reports.

**Comment by lofstrandbjorn** [comment]
C2SIM will be captured in NETN-ETR. No new or renamed HCBML modules to be included.
