### ISSUE TITLE
Harmonize FOM Module dependency across all NETN FOM v3.0 modules

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-FOM#25]
Dependencies is included as reference in modelIdentification. Should version number be included in the reference or not?!

**Comment by lofstrandbjorn** [comment]
I propose that version numbering is included in the reference. How should these references be formatted? E.g. MODULENAME + underscore + version#
<reference>
    <type>Dependency</type>
    <identification>NETN-BASE_v2.0</identification>
 </reference>

**Comment by lofstrandbjorn** [comment]
No version. Simple ref.
