### ISSUE TITLE
Develop Naming schema.

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-FOM#27]

**Comment by bergtwvd** [comment]
Attached the first proposal:

[NETN FOM Naming conventions.docx](https://github.com/AMSP-04/NETN-FOM/files/4355517/NETN.FOM.Naming.conventions.docx)

**Comment by lofstrandbjorn** [comment]
Put as .md in NETN-FOM repo and reference from ReadMe then close.

**Comment by bergtwvd** [comment]
Naming scheme proposal has been added to the README of NETN-FOM.

**Comment by lofstrandbjorn** [comment]
Reopened for review by the group.

**Comment by lofstrandbjorn** [comment]
We might need to have a discussion on the naming schema for datatypes. I am not entirely convinced that we should add "Type" at the end of each datatype. So I am opening the issue and connecting to PR for the NETN-FOM repo. for a review round.

**Comment by lofstrandbjorn** [comment]
I propose the following:

## Datatype names

A datatype name follows the same convention as a class name, with the addition below.

Since the NETN FOM modules include many legacy datatypes (that will not be changed) and since the modules are built on existing datatypes from the SISO RPR-FOM, exceptions to the naming convention may exist:

### Simple Datatype
The name of a simple datatype should end with the underlying representation and size. If relevant the unit of the datatype can be included in the name. Examples: `AltitudeMeterFloat64` which includes Meter as the unit and `MassConcentrationFloat32` which excludes the unit kg/m3.

### Enumerated Datatype
An enumeration datatype name should end with the word `Enum` + size of the datatype, e.g. `AggregateMissionEnum16`. Enumeration values should be in capital letters; the use of underscores in the value is allowed.

### Array Datatype
If the name of an array datatype is an obvious sequence of data, e.g. a name, string, list, path or polygon, no additional indication is required. All other array datatypes should include the term "ArrayOf" + the element datatype name, e.g. `ArrayOfWorldLocationStruct`. Some special array datatypes, e.g. UUID does not follow this convention.

### Fixed Record Datatype
Fixed record datatypes should end with the word `Struct`.

### Variant Record Datatype
Variant record datatypes should end with the word `VariantStruct`.

**Comment by lofstrandbjorn** [comment]
Clarify that well known abbreviations can be used as datatype names.

**Comment by lofstrandbjorn** [comment]
Dynamic Length Array Datatype
If the name of an array datatype is an obvious sequence of data, e.g. a name, string, list, path or polygon, no additional indication is required. All other array datatypes should include the term "ArrayOf" + the element datatype name, e.g. ArrayOfWorldLocationStruct. Some special array datatypes, e.g. UUID does not follow this convention.

Fixed Length Array Datatype
All fixed array datatypes should end with Array + the length of the array, e.g. SymbolIdentifierArray15.

**Comment by bergtwvd** [comment]
The naming conventions page has been updated with the information in this issue.
