### ISSUE TITLE
Name on Root-class in NETN FOM modules differ

### ISSUE THREAD

**Issue by LennartOlsson** [AMSP-04/NETN-FOM#28]
Current:
============================
Where object class starts at inherit RPR class:
AIS: RadioSignal.AisRadioSignal
Physical: Aircraft.NETN_Aircraft, ...
Aggregate: AggregateEntity.NETN_Aggregate

Starts at HLAobjectRoot:
COM: Communication...
ETR: ETR_Root...
ORG: ORG_Root...
SE: NETN_Facility... , NETN_GeoObject...

Starts at HLAinteractionRoot:
LOG: LOG_Service...
TMR: TMR.TMR_OfferTransferModellingResponsibility... 
MRM: MRM_Object.MRM_DisaggregateionRequest, MRM_Trigger

Change Proposals:
=============================
AIS: RadioSignal.AIS_RadioSignal
COM: COM_Root...
SE: SE_Root.Facility..., SE_Root.GeoObject...
TMR: TMR_Root.OfferTransferModellingResponsibility
MRM: MRM_Root.Service.DisaggregateionRequest, MRM_Root.Trigger, ...

And there are many FOM modules with empty tables, e.g MRM Object Class table. 
Maybe should these be removed.

**Comment by bergtwvd** [comment]
I like to keep `RadioSignal.AisRadioSignal`, otherwise I need to consistently prefix all classes. TBD.

**Comment by lofstrandbjorn** [comment]
For interactions:
* Changed to TMR_Interaction
* Changed to MRM_Interaction
I Propose to change LOG_Service to LOG_Interaction.
For consistency AIS_RadioSignal should be considered in **future** version of AIS Module and subclasses can then skip the prefix Ais.

**Comment by lofstrandbjorn** [comment]
For CBRN we don't make changes now. Will need to be revamped in a future version and harmonized with "Disaster" module.

**Comment by lofstrandbjorn** [comment]
For NETN-COM I propose to use NETN_CommunicationNetwork for a single object class directly on the root.

**Comment by lofstrandbjorn** [comment]
For ETR **future** version should consider changing ETR_Root to ETR_Interaction.

**Comment by lofstrandbjorn** [comment]
For ORG **future** version may consider using class names NETN_Unit and NETN_Force.

**Comment by lofstrandbjorn** [comment]
* Removed empty Object class sections for LOG and MRM modules.

**Comment by lofstrandbjorn** [comment]
Reopen new issue for future editions.
