### ISSUE TITLE
Clarify that NETN applies to more than CAX

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-FOM#38]
CAX is mentioned as example, but the wider application should be emphasized more. E.g. CTE applications (CAX can be regarded as a variant of CTE), decision support applications, analysis applications, and other types of application.

**Comment by lofstrandbjorn** [comment]
## Executive Summary

Efficient and effective use of NATO and national Modelling & Simulation (M&S) capabilities, to support training, requires standards for connecting and integrating M&S components across the training system enterprise.

The NATO Education and Training Network Federation Architecture and FOM Federation Object Model Design (NETN FAFD) document including the NETN-FOM provide architecture and design guidance for developing distributed simulation for Collective Training and Exercises (CTE), decision support, analysis, and other types of applications, including support for Computer Assisted Exercises (CAX).

The NETN-FOM focuses on technical interoperability issues in distributed simulation and provides architecture and design patterns and proposed solutions. However, it is not a complete guide on how to design a distributed simulation system. It includes architecture and design guidelines on network infrastructure, simulation infrastructure, simulation data exchange models and how to create a robust, scalable, interoperable and high performing federation of distributed simulations.
