### ISSUE TITLE
Summary of changes in 3.0 w.r.t. ETR is more than a rename

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-FOM#39]
The ETR is more than a rename of LLBML. 

Renamed LBML module to NETN-ETR (Entity Tasking and Reporting) and restructured entire module, including an update of the documentation.

**Comment by lofstrandbjorn** [comment]
### Summary of changes

* Changes in v 3.0
  * New FOM Module NETN-ORG for the representation of Organizations
  * New FOM Module NETN-SE to extend RPR-SE
  *	New FOM Module NETN-METOC for the representation of Weather
  * New FOM Module NETN-AIS for the representation of Vessel Traffic Information and Data
  * New FOM Module NETN-LOG that Merge and remove Logistics FOM Modules NETN-SCP-Base, NETN-Repair, NETN-Transport, NETN-Supply, and NETN-Storage
  * Renamed LBML module to NETN-ETR (Entity Tasking and Reporting) and restructured entire module, including an update of the documentation.
  * Major update of NETN-MRM to simplify aggregation, disaggregation, divide and merge of units.
  * Exclude FOM Module NETN-HCBML for high-level C-BML Sim-C2 interactions (in anticipation of SISO C2SIM standard).
* Changes in v 2.0
  * New FOM Module NETN-Base for standard datatypes
  * New FOM Module NETN-Physical extends RPR-Physical
  * New FOM Module NETN-CBRN for the representation of CBRN events and effects
  * New FOM Module NETN-MRM for aggregation and disaggregation of units
  * New FOM Module NETN-TMR for transfer of modelling responsibilities
  * New FOM Module NETN-HCBML for high-level C-BML Sim-C2 interactions
  * New FOM Module NETN-LLBML for low-level entity tasking and reporting
  * Renamed NETN Service Consumer-Provider FOM Module to NETN-SCP-Base
  * Replaced NETN Logistics FOM Module with NETN-Repair, NETN-Storage, NETN-Supply and NETN-Transport
* Original modules in v1.0
  * NETN Service Consumer-Provider FOM Module v1.0
  * NETN Logistics FOM Module v1.0
  * NETN Aggregate FOM Module v1.0
