### ISSUE TITLE
Initialization: extend initilization to allow for multiple dedicated federate applications 

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-FOM#42]
Text currently is:
``The scenario information can be loaded directly by simulation applications, or a dedicated federate application publishes the NETN-ORG scenario data in the federation as HLA objects. The NETN-ORG FOM module defines the Unit, EquipmentItem, and Installation object classes that can be used in the federation to publish scenario data.``

However, the design shall also allow for **multiple** dedicated federate applications that each publish a part of the NETN-ORG data, where no parts overlap in terms of the allocation of modelling responsibilities to other federates in the federation.

**Comment by lofstrandbjorn** [comment]
The scenario information can be loaded directly by simulation applications, or one or more dedicated federate applications publishes the NETN-ORG scenario data in the federation as HLA objects. The NETN-ORG FOM module defines the `Unit`, `EquipmentItem`, and `Installation` object classes that can be used in the federation to publish scenario data.
